apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: quarkus-component-e2e-gtjodrbzgz
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-code-with-quarkus-xesb
    app.kubernetes.io/part-of: pet-clinic-e2e-xejrsbcowr
  name: quarkus-component-e2e-gtjodrbzgz
  namespace: has-e2e-fhhx
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: quarkus-component-e2e-gtjodrbzgz
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: quarkus-component-e2e-gtjodrbzgz
    spec:
      containers:
      - image: quay.io/redhat-appstudio/user-workload:has-e2e-fhhx-quarkus-component-e2e-gtjodrbzgz
        imagePullPolicy: Always
        name: container-image
        resources: {}
      imagePullSecrets:
      - name: vfkpblayrr
status: {}
